name: execute-back-merge-pr-action
on: workflow_dispatch

jobs:
  execute-back-merge-pr-action:
    runs-on: ubuntu-latest
    steps:
      - name: Execute action
        uses: scane/create-back-merge-pr@v1.0.1
